version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_development
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis

  web: &web
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.development
    command: ./bin/server
    environment:
      RAILS_ENV: development
      DATABASE_URL: 'postgres://postgres:postgres@db/postgres'
      REDIS_URL: 'redis://redis:6379'
      WEBPACKER_DEV_SERVER_HOST: webpacker
    volumes:
      - .:/app
      - bundle-cache:/usr/local/bundle:cached
      - node-cache:/app/node_modules:cached
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

  webpacker:
    <<: *web
    command: bin/webpack-dev-server
    ports:
      - 3035:3035
    environment:
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    depends_on:
      - web

volumes:
  db-data:
  bundle-cache:
  node-cache:
