FROM ruby:2.7.1-alpine

RUN apk --update add build-base \
                     tzdata \
                     nodejs \
                     yarn \
                     postgresql-dev \
                     postgresql-client \
                     libxslt-dev \
                     libxml2-dev \
                     imagemagick

RUN mkdir /app

WORKDIR /app

COPY Gemfile* ./
COPY . /app

RUN gem install bundler

RUN bundle install
