default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { 'postgres://postgres:postgres@db/postgres' } %>_development

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { 'postgres://postgres:postgres@db/postgres' } %>_test

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { '' } %>
